[/Script/Engine.GameUserSettings]
; === QUALITÉ GRAPHIQUE PAR DÉFAUT : MEDIUM ===
; 0=Low  1=Medium  2=High  3=Epic
ScalabilityQuality.ResolutionQuality=75.000000
ScalabilityQuality.ViewDistanceQuality=1
ScalabilityQuality.AntiAliasingQuality=1
ScalabilityQuality.ShadowQuality=1
ScalabilityQuality.GlobalIlluminationQuality=1
ScalabilityQuality.ReflectionQuality=1
ScalabilityQuality.PostProcessQuality=1
ScalabilityQuality.TextureQuality=1
ScalabilityQuality.EffectsQuality=1
ScalabilityQuality.FoliageQuality=1
ScalabilityQuality.ShadingQuality=1

; === OPTIONS FENÊTRE ===
bUseVSync=False
bUseDynamicResolution=False
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
FullscreenMode=1
LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1
Version=5

; === FRAMERATE ===
FrameRateLimit=60.000000
